In [25]:
import os
import glob
import pandas as pd
os.chdir("resources")

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'resources'

In [34]:
# make sure all files in same formate "csv"
EC = pd.read_excel("1/2019-01-10 to 01-20.xlsx")
ec=EC.drop(['new_confirmed'], axis =1)
ec.to_csv("2019-01-10 to 01-20.csv")
ec.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Hubei,China,1/11/2020 22:00:00 AM,41.0,1.0,2.0
1,Hubei,China,1/12/2020 22:00:00 AM,41.0,1.0,6.0
2,Hubei,China,1/13/2020 22:00:00 AM,41.0,1.0,7.0
3,Hubei,China,1/14/2020 22:00:00 AM,41.0,1.0,7.0
4,Hubei,China,1/15/2020 22:00:00 AM,41.0,1.0,7.0

In [35]:
df = pd.read_csv('01-22-2020.csv')
df.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
1,Beijing,Mainland China,1/22/2020 17:00,14.0,NaN,NaN
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,NaN,NaN
3,Fujian,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
4,Gansu,Mainland China,1/22/2020 17:00,NaN,NaN,NaN

In [29]:
#Use glob to match the pattern ‘csv’
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [30]:
#Combine all files in the list and export as CSV
jan = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
jan.to_csv( "1/combined_csv.csv", index=False, encoding='utf-8-sig')

C:\Users\super\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [32]:
len(jan)

2840

In [33]:
jan

,Confirmed,Country/Region,Deaths,Last Update,Province/State,Recovered,Unnamed: 0
0,1.0,Mainland China,NaN,1/22/2020 17:00,Anhui,NaN,NaN
1,14.0,Mainland China,NaN,1/22/2020 17:00,Beijing,NaN,NaN
2,6.0,Mainland China,NaN,1/22/2020 17:00,Chongqing,NaN,NaN
3,1.0,Mainland China,NaN,1/22/2020 17:00,Fujian,NaN,NaN
4,NaN,Mainland China,NaN,1/22/2020 17:00,Gansu,NaN,NaN
...,...,...,...,...,...,...,...
17,1.0,Japan,0.0,1/17/2020 22:00:00 PM,NaN,1.0,17.0
18,2.0,Thanland,0.0,1/21/2020 22:00:00 PM,NaN,0.0,18.0
19,1.0,Japan,0.0,1/21/2020 22:00:00 PM,NaN,1.0,19.0
20,1.0,korean,0.0,1/21/2020 22:00:00 PM,NaN,1.0,20.0
21,291.0,China,3.0,1/21/2020 22:00:00 PM,NaN,27.0,21.0