In [1]:
import os
import glob
import pandas as pd
os.chdir("resources")

In [9]:
# make sure all files in same formate "csv"
EC = pd.read_excel("2019-01-10 to 01-20.xlsx")
EC.to_csv("2019-01-10 to 01-20.csv")
EC.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,new_confirmed
0,Hubei,China,1/11/2020 22:00:00 AM,41.0,1.0,2.0,0.0
1,Hubei,China,1/12/2020 22:00:00 AM,41.0,1.0,6.0,0.0
2,Hubei,China,1/13/2020 22:00:00 AM,41.0,1.0,7.0,0.0
3,Hubei,China,1/14/2020 22:00:00 AM,41.0,1.0,7.0,0.0
4,Hubei,China,1/15/2020 22:00:00 AM,41.0,1.0,7.0,0.0

In [10]:
EC.drop(['new_confirmed'], axis =1)

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Hubei,China,1/11/2020 22:00:00 AM,41.0,1.0,2.0
1,Hubei,China,1/12/2020 22:00:00 AM,41.0,1.0,6.0
2,Hubei,China,1/13/2020 22:00:00 AM,41.0,1.0,7.0
3,Hubei,China,1/14/2020 22:00:00 AM,41.0,1.0,7.0
4,Hubei,China,1/15/2020 22:00:00 AM,41.0,1.0,7.0
5,Hubei,China,1/16/2020 22:00:00 PM,41.0,2.0,12.0
6,Hubei,China,1/17/2020 22:00:00 PM,45.0,2.0,15.0
7,Hubei,China,1/18/2020 22:00:00 PM,62.0,2.0,19.0
8,Hubei,China,1/198/2020 22:00:00 PM,121.0,3.0,24.0
9,Hubei,China,1/20/2020 22:00:00 PM,198.0,3.0,25.0
10,Hubei,China,1/21/2020 22:00:00 PM,270.0,3.0,27.0
11,Shanghai,China,1/21/2020 22:00:00 PM,2.0,0.0,0.0
12,Beijing,China,1/21/2020 22:00:00 PM,5.0,0.0,0.0
13,guangdong,NaN,1/21/2020 22:00:00 PM,14.0,0.0,0.0
14,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Thanland,1/17/2020 22:00:00 PM,1.0,0.0,0.0
17,NaN,Japan,1/17/2020 22:00:00 PM,1.0,0.0,1.0
18,NaN,Thanland,1/21/2020 22:00:00 PM,2.0,0.0,0.0
19,NaN,Japan,1/21/2020 22:00:00 PM,1.0,0.0,1.0
20,NaN,korean,1/21/2020 22:00:00 PM,1.0,0.0,1.0
21,NaN,China,1/21/2020 22:00:00 PM,291.0,3.0,27.0

In [11]:
df = pd.read_csv('01-22-2020.csv')

In [ ]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]